[tools]
buf = "latest"
dbmate = "2"
dive = "latest"
erlang = "27"
gleam = "1.4"
go = "1.23"
kubectx = "latest"
lazygit = "latest"
node = "lts"
python = ["3.8", "3.12"]
rebar = "3"
ruby = "3.3"

[settings]
python_compile = true
python_venv_auto_create = true
trusted_config_paths = ["~/.dotfiles/mise/"]
