[tools]
buf = "latest"
dbmate = "latest"
dive = "latest"
erlang = "latest"
gleam = "latest"
go = "latest"
kubectx = "latest"
lazygit = "latest"
node = "lts"
python = "latest"
rebar = "latest"
ruby = "latest"
sops = "latest"
stern = "latest"

[settings]
python_compile = true
python_venv_auto_create = true
trusted_config_paths = ["~/.dotfiles/mise/"]
