[tools]
go = "latest"
node = "lts"
python = "latest"
ruby = "latest"

[settings]
python_compile = true
python_venv_auto_create = true
trusted_config_paths = ["~/dotfiles/mise/"]
idiomatic_version_file_enable_tools = ["node", "python", "ruby"]
